version: '3.8'

networks:
  todo-net:

volumes:
  pgdata:
  
services:
  web-api:
    build: ./web
    command: python app.py
    ports:
      - target: 8080
        published: 5002
    expose:
      - "8080"
    networks:
      - todo-net
    
  db:
    container_name: db_postgres_dev
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net
    
  